{
  # Import all your configuration modules here
  imports = [
    ./bufferline.nix
    ./bufdelete.nix
    ./bullets.nix
    ./pbcopy.nix
    ./colorscheme.nix
    ./ccc.nix
    ./cloak.nix
    ./colorizer.nix
    ./keymaps.nix
    ./kulala.nix
    ./treesitter.nix
    ./snacks.nix
    ./trouble.nix
    ./blink.nix
    ./conform.nix
    ./lspconfig.nix
    ./which-key.nix
    ./git.nix
    ./glow.nix
    ./icons.nix
    ./noice.nix
    ./obsidian.nix
    ./airline.nix
    ./telescope.nix
    ./harpoon.nix
    ./oil.nix
    ./oil-git-status.nix
    ./opencode.nix
    ./dap.nix
    ./render-markdown.nix
    ./neotest.nix
    ./navic.nix
    ./nix.nix
    ./aerial.nix
    ./navbuddy.nix
    ./treesitter-context.nix
    ./ts-autotag.nix
    ./lazygit.nix
    ./leap.nix
    ./flash.nix
    ./mini.nix
    ./persistence.nix
    ./tmux-navigator.nix
    ./toggleterm.nix
    ./todo-comments.nix
    ./comment.nix
    ./sleuth.nix
    ./fidget.nix
    ./lazydev.nix
    ./editorconfig.nix
    ./supermaven.nix
    ./startify.nix
    ./arrow.nix
    ./twilight.nix
    ./vimtex.nix
    ./wtf.nix
    ./vim-dadbod.nix
    ./vim-dadbod-completion.nix
    ./vim-dadbod-ui.nix
  ];
}
